
spring.datasource.url=jdbc:h2:mem:kanbandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console gráfico em http://localhost:1001/h2-console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:seed/import.sql
spring.jpa.defer-datasource-initialization=true
