# App
spring.application.name=kanban-api

# Server
server.port=1001

# Profile
spring.profiles.active=dev

# # Database
# spring.datasource.url=jdbc:postgresql://localhost:3001/db_kanban
# spring.datasource.username=littlesekii
# spring.datasource.password=123

# # Hibernate/JPA
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true